name: Cypress E2E

on: pull_request

jobs:
  cypress-e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: bun test:ci
          working-directory: ./apps/docs