name: Cypress E2E

on: pull_request

jobs:
  cypress-e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # -y to output yarn.lock file as cypress-io/github-action@v6 doesnt support bun
      # https://github.com/cypress-io/github-action/issues/585
      - run: bun install -y 
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: bun test:ci
          working-directory: ./apps/docs