name: Cypress E2E

on: pull_request

jobs:
  cypress-e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deps
        run: npm i

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:ci
          working-directory: ./apps/docs